apiVersion: v1
kind: Namespace

metadata:
  name: development
  labels:
    name: development

---
apiVersion: v1
kind: Pod

metadata:
  namespace: development
  name: nginx-pod-test

spec:
  containers:
    - name: nginx-test
      image: nginx:latest
      ports:
        - containerPort: 80
