apiVersion: v1
kind: Namespace

metadata:
  name: development
  labels:
    name: development

---
apiVersion: v1
kind: ServiceAccount

metadata:
  namespace: development
  name: nginx-test-pod-service-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  namespace: development
  name: nginx-test-pod-reader

rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list  "]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  namespace: development
  name: role-binding-nginx-to-listing-pods

roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: Role
  name: nginx-test-pod-reader


subjects:
  - kind: ServiceAccount
    name: nginx-test-pod-service-account
    namespace: development

---
apiVersion: v1
kind: ConfigMap

metadata:
  name: nginx-config
  namespace: development

data: 
  index: |
    <h1>Hello world!</h1>
    <p>This is HTML from Kubernetes ConfigMap</p>

  different-index: |
    <h1>Hello world from different pod!</h1>
    <p>This is a load balancing test</p>

  hello: |
    <h2>Another hello world!<h2>

  kube-info-config: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
          root /usr/share/nginx/html-kube-info;
          index kube-info.html;
      }

      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }

---
apiVersion: v1
kind: Pod

metadata:
  namespace: development
  name: nginx-pod-test
  labels:
    app: nginx-test

spec:
  serviceAccountName: nginx-test-pod-service-account

  initContainers:
    - name: page-generator
      image: bitnami/kubectl
      command: 
        - /bin/bash
        - "-c"
      args:
        - 'kubectl get pods -n development > /output/kube-info/kube-info.html'
      volumeMounts:
        - name: page-generator-output-volume
          mountPath: /output/kube-info

  containers:
    - name: nginx-test
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d

        - name: page-generator-output-volume
          mountPath: /usr/share/nginx/html-kube-info
  
  volumes:
    - name: nginx-config-volume
      configMap:
        name: nginx-config
        items: 
          - key: kube-info-config  
            path: kube-info.conf

    - name: page-generator-output-volume
      emptyDir:
        sizeLimit: 50M

---
# This is for testing load balancing "by hand"
apiVersion: v1
kind: Pod

metadata:
  namespace: development
  name: nginx-another-pod-test
  labels:
    app: nginx-test

spec:
  containers:
    - name: nginx-test
      image: nginx:latest
      ports: 
        - containerPort: 80
      volumeMounts:
        - name: nginx-config-volume
          mountPath: /usr/share/nginx/html

  volumes:
    - name: nginx-config-volume
      configMap:
        name: nginx-config
        items:
          - key: different-index
            path: index.html
          - key: hello
            path: hello.html

---
apiVersion: v1
kind: Service

metadata:
  namespace: development
  name: nginx-test-service

spec:
  type: ClusterIP

  clusterIP: 10.96.0.9

  selector: 
    app: nginx-test
  
  ports:
    - protocol: TCP
      # As a test, we will create cluster IP on port 400
      port: 4000
      targetPort: 80
