
apiVersion: v1
kind: Service

metadata:
  namespace: development
  name: nginx-test-service

spec:
  type: ClusterIP

  clusterIP: 10.96.0.9

  selector: 
    app: nginx-test
  
  ports:
    - protocol: TCP
      # As a test, we will create cluster IP on port 400
      port: 4000
      targetPort: 80
