apiVersion: v1
kind: Pod

metadata:
  namespace: volumes-test
  name: nginx-pod
  labels:
    app: nginx-volume-test

spec:
  containers:
    - name: nginx
      image: "nginx:latest"
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: test-pvc

  volumes:
    - name: test-pvc
      persistentVolumeClaim:
        claimName: test-persistent-volume-claim

---
apiVersion: v1
kind: Pod

metadata:
  namespace: volumes-test
  name: nginx-pod-2
  labels:
    app: nginx-volume-test

spec:
  containers:
    - name: nginx
      image: "nginx:latest"
      ports: 
        - containerPort: 80 
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: test-pvc
  
  volumes:
    - name: test-pvc
      persistentVolumeClaim:
        claimName: test-persistent-volume-claim
