apiVersion: v1
kind: Service

metadata:
  name: nginx-service
  namespace: volumes-test

spec:
  selector:
    app: nginx-volume-test

  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      nodePort: 30001

  type: NodePort
