apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition

metadata:
  name: mycustomresources.jirifilip.github.com
  namespace: crd-test

spec:
  group: jirifilip.github.com

  names:
    kind: MyCustomResource
    plural: mycustomresources
    categories:
      - all

  scope: Namespaced

  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema: 
        type: object
        properties:
          spec:
            type: object
            required:
              - propertyA
              - propertyB
            properties:
              propertyA:
                type: integer
              propertyB:
                type: string
